### ISSUE TITLE
Swift Symbols not demangled

### ISSUE THREAD

**Issue by jhurray** [getsentry/self-hosted#1300]
### Version

9.0.0

### Steps to Reproduce

1. Install & set up iOS SDK version 5.2.2 pointing to hosted on-prem project
2. Crash or log an error
2. View error on hosted sentry instance
3. See mangled swift symbols like `s14ConsumerPortal0B17WebViewControllerC13developerMenu33_DD44BF3E57F699903F0FBB8CB98E8FB9LLAA09DeveloperG0CvgyAG6ActionOcfU0_ `

### Expected Result

Expect to see `closure #2 (ConsumerPortal.DeveloperMenu.Action) -> () in ConsumerPortal.PortalWebViewController.(developerMenu in _DD44BF3E57F699903F0FBB8CB98E8FB9).getter : ConsumerPortal.DeveloperMenu`

### Actual Result

See steps to repro

This forum post details it as well https://forum.sentry.io/t/ios-sdk-swift-symbols-not-demangled/15968

I'm guessing from reading other posts that 9.0.0 on-prem is pointing towards an older version of symbolic that does not demangle newer versions fo swift properly. If that's the case, is it possible to point our on-prem version to the newest symbolic version to fix the issue? Upgrading beyond 9.0.0 isn't an option for us at the moment

**Comment by chadwhitacre** [comment]
Dang, version 9? That's ancient! 😂

Can you repro with a modern version?

**Comment by jhurray** [comment]
Haha yeah it's really old. I can try to repel with a newer version if there's a low barrier there. 

Really what I'm looking for is an indication of whether this is a solvable problem or not. It's a bit opaque what the relationship between symbolic & on-prem is, and whether an "ancient" version could use the most up to date symbolic version.

**Comment by chadwhitacre** [comment]
> whether an "ancient" version could use the most up to date symbolic version.

Yeah that's definitely gonna be a DIY adventure. I guess you could try running with `SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly` in your [`.env.custom`](https://develop.sentry.dev/self-hosted/#configuration) and see what happens? :)

**Comment by jhurray** [comment]
@chadwhitacre we set `SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly` as an environment variable in our docker container for web and this did not seem to work :/ 

Any idea if symbolicator is run on worker or cron instead? We're trying those now but also just curious about at what point we should give up 😅 

Any other suggestions?

**Comment by chadwhitacre** [comment]
> Any idea if symbolicator is run on worker or cron instead?

There's a symbolicator container. :P

**Comment by aminvakil** [comment]
> Any other suggestions?

You may try upgrading to recent releases, consider [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops) though.

**Comment by jhurray** [comment]
@chadwhitacre thanks! Exactly what we're looking for. We're flying a little blind here and this is super helpful 

Below is a copy of our YAML setup with env vars redacted. 
- We don't have a `.env` file and we set env vars in the yaml file directly, will that work or do we _need_ an `.env` file?
- I'm assuming we should also run a `sentry-symbolicator` container?
  -  If yes what command should it run?
  - Should we add the `SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly` as an env var to that container?

<details>
```yaml
  SentryWebTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn: SentryFilestoreS3Bucket
    Properties:
      ContainerDefinitions:
      -
        Name: 'sentry-web'
        Image: !Ref 'Image'
        Memory: '2048'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: "ecs"
            awslogs-region: "us-east-1"
            awslogs-stream-prefix: !Join ['-', ['sentry-web', !Ref 'Environment']]
        Command: ["run", "web"]
        Environment:
          - Name: [...]
            Value: [...]
          - [...]
        PortMappings:
          -
            ContainerPort: 9000

  SentryUpgrade:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'Cluster'
      DesiredCount: 0
      TaskDefinition: !Ref 'SentryUpgradeTask'

  SentryUpgradeTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn: SentryFilestoreS3Bucket
    Properties:
      ContainerDefinitions:
      -
        Name: 'sentry-upgrade'
        Image: !Ref 'Image'
        Memory: '2048'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: "ecs"
            awslogs-region: "us-east-1"
            awslogs-stream-prefix: !Join ['-', ['sentry-upgrade', !Ref 'Environment']]
        Command: ["upgrade", "--noinput"]
        Environment:
          - Name: [...]
            Value: [...]
          - [...]

  SentryCron:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'Cluster'
      DesiredCount: !Ref 'SentryCronDesiredCount'
      TaskDefinition: !Ref 'SentryCronTask'

  SentryCronTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn: SentryFilestoreS3Bucket
    Properties:
      ContainerDefinitions:
      -
        Name: 'sentry-cron'
        Image: !Ref 'Image'
        Memory: '1024'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: "ecs"
            awslogs-region: "us-east-1"
            awslogs-stream-prefix: !Join ['-', ['sentry-cron', !Ref 'Environment']]
        Command: [
        "run",
        "cron"
        ]
        Environment:
          - Name: [...]
            Value: [...]
          - [...]

  SentryWorker:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'Cluster'
      DesiredCount: !Ref 'SentryWorkerDesiredCount'
      TaskDefinition: !Ref 'SentryWorkerTask'

  SentryWorkerTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref 'ECSTaskRole'
      ContainerDefinitions:
      -
        Name: 'sentry-worker'
        Image: !Ref 'Image'
        Memory: '1024'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: "ecs"
            awslogs-region: "us-east-1"
            awslogs-stream-prefix: !Join ['-', ['sentry-worker', !Ref 'Environment']]
        Command: [
        "run",
        "worker"
        ]
        Environment:
          - Name: [...]
            Value: [...]
          - [...]
```
<\details>
