### ISSUE TITLE
Install with other services

### ISSUE THREAD

**Issue by reyesmfabian** [getsentry/self-hosted#1320]
### Problem Statement

Hi, at the moment I have a docker host running some services with automatic self signed SSL certificates. 

This is my docker-compose.yml

```
version: '3'

services:
  image_name:
    image: myimage
    container_name: myimage
    restart: always
    environment:
      - VIRTUAL_HOST=mydomain.com
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=mail@mydomain.com
    volumes:
      - ./myimage
    expose:
      - "80"
    depends_on:
      - nginx-proxy
      - letsencrypt

  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: nginxproxy/acme-companion:2.0.2
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes: 
  certs:
  html:
  vhostd:
  dhparam:
  acme:
```

Is it possible to install sentry under this same proxy? so that it takes the certificate from the service already created? I have tried and it loads with the https but many services do not work.
