### ISSUE TITLE
Unable to see uploaded source maps

### ISSUE THREAD

**Issue by mle-moni** [getsentry/self-hosted#1441]
### Version

21.10.0

### Steps to Reproduce

Hi!
I have a problem when uploading source files:
- I uploaded source maps with sentry-cli
```
sentry-cli releases new -p frontend sentry-test-06
sentry-cli releases -p frontend files sentry-test-06 upload-sourcemaps ./apps/cra/build/static/js/
sentry-cli releases finalize sentry-test-06
```
- It showed not errors
- I went to `/settings/sentry/projects/frontend/source-maps/sentry-test-06` on our sentry website

### Expected Result

I was expecting to: see the uploaded source maps for this release

### Actual Result

But the ui shows:

![image](https://user-images.githubusercontent.com/57536419/166947555-e4c08e88-b1ac-464b-9720-3b5e7d946047.png)

additionnal infos:
- related sentry config:
```yml
filestore.backend: 'filesystem'
filestore.options:
  location: '/opt/sentry/data/files'
dsym.cache-path: '/opt/sentry/data/dsym-cache'
releasefile.cache-path: '/opt/sentry/data/releasefile-cache'
```
- on the sentry_onpremise_web container in `/opt/sentry/data/files`, we can see that there is what looks like compressed files
