### ISSUE TITLE
Provide App Manifest for Setting Up Slack in Self-Hosted Installations

### ISSUE THREAD

**Issue by timm0e** [getsentry/self-hosted#1912]
Slack offers a new way to set up apps using YAML/JSON files called [App Manifests](https://api.slack.com/reference/manifests).

Providing such a manifest would make setting up the Slack integration on self-hosted installations much easier and faster, since one can skip the many steps required.

As an example: I've just completed a setup of the integration, which results in the following manifest (just open Features > App Manifest to view the manifest of the current app) :
```yaml
display_information:
  name: Sentry
  description: Sentry
  background_color: "#584674"
features:
  bot_user:
    display_name: Sentry
    always_online: true
  slash_commands:
    - command: /sentry
      url: https://<your.domain>/extensions/slack/commands/
      description: Interact with Sentry
      should_escape: false
  unfurl_domains:
    - your.domain
oauth_config:
  redirect_urls:
    - https://<your.domain>/extensions/slack/setup/
  scopes:
    user:
      - links:read
      - users:read
      - users:read.email
    bot:
      - channels:read
      - chat:write
      - chat:write.customize
      - chat:write.public
      - commands
      - groups:read
      - im:history
      - im:read
      - links:read
      - links:write
      - team:read
      - users:read
settings:
  allowed_ip_address_ranges:
    - <your.instance.ip>/32
  event_subscriptions:
    request_url: https://<your.domain>/extensions/slack/event/
    user_events:
      - link_shared
    bot_events:
      - link_shared
      - message.im
  interactivity:
    is_enabled: true
    request_url: https://<your.domain>/extensions/slack/action/
    message_menu_options_url: https://<your.domain>/extensions/slack/options-load/
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```
