### ISSUE TITLE
Relay pod crashloopbackoff - Unable to connect to sasl_plaintext auth based kafka

### ISSUE THREAD

**Issue by IamGroot19** [getsentry/self-hosted#2106]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

NA

### Docker Compose Version

NA

### Steps to Reproduce

We are running on Sentry Helm chart on kubernetes (chart version 17.10.1). 
We have a kerberos based kafka authentication setup which we'd like to use for sentry.

After rendering the helm chart, the Relay configuration looks like below
```
relay:
      mode: proxy
      upstream: "http://release-name-sentry-web:9000/"
      host: 0.0.0.0
      port: 3000

    processing:
      enabled: true

      kafka_config:
        - name: "bootstrap.servers"
          value: "server1.com:9092,server2.com:9092,sserver3.com:9092"
        - name: "message.max.bytes"
          value: 50000000  # 50MB or bust
        - name: "security.protocol"
          value: sasl_plaintext
        - name: "sasl.mechanism"
          value: "GSSAPI"
        - name: "sasl.kerberos.service.name"
          value: "kafka"
        - name: "sasl.kerberos.keytab"
          value: "/relaycfg/sentry.keytab"
        - name: "sasl.kerberos.principal"
          value: "sentry@TEST.CONFLUENT.IO"
        - name: "log_level"
          value: 7
        
      redis: "redis://:@release-name-sentry-redis-master:6379"
      topics:
        metrics_transactions: ingest-performance-metrics
        metrics_sessions: ingest-metrics

    # Additional relay config
    logging:
      level: trace
```

We came across couple of other github issues ([here](https://github.com/getsentry/relay/issues/971) and [here](https://github.com/getsentry/relay/issues/879)) with same error message but those were for SSL based authentication.

Can someone help us here with how to troubleshoot this & how to make relay work with kafka authentication?

### Expected Result

To be able to connect to kafka & start writing events to it

### Actual Result

The logs printed by Relay pod as below
```
2023-04-24T05:56:24Z [relay::setup] INFO: launching relay from config folder /work/.relay
2023-04-24T05:56:24Z [relay::setup] INFO:   relay mode: proxy
2023-04-24T05:56:24Z [relay::setup] INFO:   relay id: ce104c4b-fa4c-420c-89e6-vgthjoi3b66af
2023-04-24T05:56:24Z [relay::setup] INFO:   public key: cdAcUZyNMu8atC2-fsgbvrthrdsWHdOeBCN0WxiTChqY
2023-04-24T05:56:24Z [relay::setup] INFO:   log level: TRACE
2023-04-24T05:56:24Z [relay_server::actors::upstream] INFO: upstream relay started
2023-04-24T05:56:24Z [relay_log::utils] ERROR: could not initialize kafka producer
```
- note: Even with trace level logging enabled, we are not getting sufficient information to figure out what went wrong. Likewise, enabling debug logging at librdkafka level also didnt give us any helpful information
