### ISSUE TITLE
Sentry-data volume cleanup

### ISSUE THREAD

**Issue by ultramaks** [getsentry/self-hosted#2121]
### Problem Statement

The issue has been opened [here](https://forum.sentry.io/t/sentry-data-volume-cleanup/15227) but has not been answered yet
We have a self-hosted Sentry version 23.4.0 (upgraded from 22.9.0)
There is a container _sentry-self-hosted_sentry-cleanup_1_ which is meant to clean the **database** date. It's created in _docker-compose.yml_ by the following code
```
  sentry-cleanup:
    <<: *sentry_defaults
    image: sentry-cleanup-self-hosted-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: sentry-self-hosted-local
    entrypoint: "/entrypoint.sh"
    command: '"0 0 * * * gosu sentry sentry cleanup --days 
```
But we also have the _/data_ directory in the volume with the files that do not get deleted by any service and the size of the directory constantly grows
```
# du -sh /data
99G     /data
```
I wonder if I can put something like
`    command: '"0 0 * * * find /data/files/ -mindepth 1 -mtime +15 -delete"'
into the _docker-compose.yml_ file to automate the process of cleaning up the disk space (currently we do it manually from time to time) oк it can breaky any processes in sentry? Are there any other ways?

**PS** we have a standard DB cleanup set up for 15 days
```
# crontab -l
SHELL=/bin/bash
BASH_ENV=/container.env
0 0 * * * gosu sentry sentry cleanup --days 15 > /proc/1/fd/1 2>/proc/1/fd/2
```
