### ISSUE TITLE
Sentry-data volume cleanup

### ISSUE THREAD

**Issue by kmentch** [getsentry/self-hosted#2313]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.8

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Check docker volume disk usage with du (`695G	./sentry-data`)
2. Run cleanup with a number of days less than what gets run on cron daily (`SENTRY_EVENT_RETENTION_DAYS=15`), so choose 12 or 10 to cleanup more data.
3. Expect sentry-data disk usage to go down.

### Expected Result

Sentry-data disk usage is lower than previous

### Actual Result

Sentry-data disk usage is exactly the same before running cleanup.

Would like to know whats actually stored in sentry-data/_data and if theres a way to clean it up, the same goes for the kafka volume too.

**Comment by azaslavsky** [comment]
Is it possible that you have a lot of attachments? The `sentry cleanup` command that this is executing only deletes rows in Postgres, it doesn't touch attached files.

One thing you could try (after backing up `./sentry-data`, of course!) is just manually deleting everything in `.sentry-data` that is older than 15 days. If that solves your problem (ex, you see that folder drop by 100s of GBs), could you please report back? We can look into modifying the cleanup script to purge these old attachment files as well.

**Comment by kmentch** [comment]
Doing a cleanup of any file that was created longer than 100 days so far has cleaned up almost 500GB. I am reviewing with my team what these files could be so we can better understand what is being saved here. But it would be nice if this was included in the cleanup process as well.

**Comment by hubertdeng123** [comment]
Cleanup for us is more about data retention for compliance in prod. If you'd like a job to handle the cleanup of disk space as well, you can create a job similar to `vroom-cleanup` that is defined in `docker-compose.yml`. It should look something like this

```
disk-cleanup:
<<: *restart_policy
    image: sentry-cleanup-self-hosted-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: sentry-self-hosted-local
    entrypoint: "/entrypoint.sh"
    command: '"0 0 * * * find /_data -type f -mtime +$SENTRY_EVENT_RETENTION_DAYS -delete"'
    volumes:
      - sentry-data:/_data
```
