### ISSUE TITLE
[Errno 111] Connection refused when trying to send email using external smtp server

### ISSUE THREAD

**Issue by juliangiebel** [getsentry/self-hosted#2368]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.3

### Steps to Reproduce

1. Configure external smtp server in `sentry/config.yml`
2. Start sentry
3. Send test email

I've followed the setup guide and the guide for configuring email:
https://develop.sentry.dev/self-hosted/
https://develop.sentry.dev/self-hosted/email/

My email server is hosted on the same machine on a docker container

.env file:
```env
COMPOSE_PROJECT_NAME=sentry-self-hosted
SENTRY_EVENT_RETENTION_DAYS=90
# You can either use a port number or an IP:PORT combo for SENTRY_BIND
# See https://docs.docker.com/compose/compose-file/#ports for more
SENTRY_BIND=9000
# Set SENTRY_MAIL_HOST to a valid FQDN (host/domain name) to be able to send emails!
#SENTRY_MAIL_HOST=example.com
SENTRY_IMAGE=getsentry/sentry:23.8.0
SNUBA_IMAGE=getsentry/snuba:23.8.0
RELAY_IMAGE=getsentry/relay:23.8.0
SYMBOLICATOR_IMAGE=getsentry/symbolicator:23.8.0
VROOM_IMAGE=getsentry/vroom:23.8.0
WAL2JSON_VERSION=latest
HEALTHCHECK_INTERVAL=30s
HEALTHCHECK_TIMEOUT=1m30s
HEALTHCHECK_RETRIES=10
```

sentry/config.yml mail config (I replaced my domain with: my-server.dev. My tld is .dev):
```yml
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'mail.my-server.dev'
mail.port: 587
mail.username: 'noreply@my-server.dev'
mail.password: '******'
mail.use-tls: true
mail.use-ssl: false

# NOTE: The following 2 configs (mail.from and mail.list-namespace) are set
#       through SENTRY_MAIL_HOST in sentry.conf.py so remove those first if
#       you want your values in this file to be effective!


# The email address to send on behalf of
mail.from: 'noreply@my-server.dev'
# mail.from: 'System Administrator <root@localhost>'

# The mailing list namespace for emails sent by this Sentry server.
# This should be a domain you own (often the same domain as the domain
# part of the `mail.from` configuration parameter value) or `localhost`.
mail.list-namespace: 'my-server.dev'
````

I followed the suggestion from the note and commented out the two email related lines in sentry/sentry.conf.py

This didn't work. My email server is properly set up, has been running for a few years now and is being used by other services I host for outgoing email.
I tried different combinations like putting the lines in the python file back.
I also looked through the forum and the gh issues.

### Expected Result

Email sends successfully

### Actual Result

sentry-self-hosted-web-1                                       | 16:54:34 [INFO] sentry.superuser: superuser.request (url='http://bugs.-/api/0/internal/mail/' method='POST' ip_address='-' user_id=1)
sentry-self-hosted-web-1                                       | 16:54:34 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.internal.mail.InternalMailEndpoint' response=500 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/internal/mail/' caller_ip='-' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.01631331443786621 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1                                       | 16:54:34 [ERROR] django.request: Internal Server Error: /api/0/internal/mail/ (status_code=500 request=<WSGIRequest: POST '/api/0/internal/mail/'>)
