### ISSUE TITLE
Add Developer Metrics

### ISSUE THREAD

**Issue by aldy505** [getsentry/self-hosted#2698]
### Problem Statement

Sentry has Developer Metrics in alpha. We should bring that into self-hosted after GA.

### Solution Brainstorm

Discussion: https://github.com/getsentry/sentry/discussions/58584
Feature docs: https://develop.sentry.dev/delightful-developer-metrics/
SDK: https://develop.sentry.dev/sdk/metrics/

SDK guide on Python: https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/

**Comment by aldy505** [comment]
To enable the feature, you'd need to edit your `sentry/sentry.conf.py` file and add these feature flags:

```python
SENTRY_FEATURES.update(
  {
    feature: True
    for feature in (
      # ......
      # For DDM
      "organizations:ddm-ui",
      "organizations:custom-metrics",
      "organizations:ddm-experimental",
      "organizations:use-metrics-layer-in-alerts"
    )
  }
)
```

Add new Snuba container on your `docker-compose.yml`:

```yaml
  snuba-generic-metrics-gauges-consumer:
    <<: *snuba_defaults
    command: consumer --storage generic_metrics_gauges_raw --consumer-group snuba-gen-metrics-gauges-consumers --auto-offset-reset=latest --max-batch-time-ms 750 --no-strict-offset-reset
```

 Then do `./install.sh` all over again.
