### ISSUE TITLE
Install Sentry on Windows with Docker

### ISSUE THREAD

**Issue by truthz03** [getsentry/self-hosted#2834]
Hi,

because it is not possible for me to follow the official installation guid because this is only possible on Linux, I tried to create my own docker-compose file like this from @hubertdeng123 but I always get this error: !! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")

Is there someting else to do to be able to start Sentry?
I tried it with:
   image: getsentry/sentry:dfdf4fb
   image: getsentry/sentry:latest
   image: getsentry/sentry:23.12.1
but always the same error.

@hubertdeng123 
> I need more info, since I cannot reproduce this.

I'm also able to reproduce the problem with the dockerfile provided by @OlegYurchik. Have you tried it?

>  Is there a reason why you are using a Sentry image tagged with a specific commit SHA?

I think he chose that tag so that you can reproduce the problem using that very same version.

Here's my docker-compose.yml:
```
version: "3.9"
services:
  redis:
    container_name: "redis"
    image: redis:latest
    restart: "unless-stopped"
    ports:
      - 6379:6379
  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: "unless-stopped"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
  sentry:
    container_name: "sentry"
    image: getsentry/sentry:latest
    restart: "unless-stopped"
    ports:
      - 9000:9000
    links:
      - "redis"
      - "postgres"
    environment:
      SENTRY_REDIS_HOST: "redis"
      SENTRY_POSTGRES_HOST: "postgres"
      SENTRY_DB_USER: "postgres"
      SENTRY_DB_PASSWORD: "secret"
      SENTRY_SECRET_KEY: "lMHMxH6GXGd8rt5j6vnMz19R9RpJgOJ9"
```

_Originally posted by @Moreno-Gentili in https://github.com/getsentry/self-hosted/issues/2584#issuecomment-1863579349_
