### ISSUE TITLE
Email sending error

### ISSUE THREAD

**Issue by weirdvic** [getsentry/self-hosted#2868]
### Self-Hosted Version

24.3.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.17.2

### Steps to Reproduce

I'm trying to set up email sending over Google's smtp servers.
Sentry's `smtp` service is not used and related parts are commented out of `docker-compose.yml`
Here is my email related settings from `config.yml`
```yaml
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.google.com'
mail.port: 587
mail.username: 'username@workdomain.com'
mail.password: 'apppasswordforgmail'
mail.use-tls: true
mail.use-ssl: false
# The email address to send on behalf of
mail.from: 'sentry@workdomain.com'
```

When I try to send a test email from `/manage/status/mail/` I get these errors in logs:
```
sentry-web-1  | 16:18:29 [INFO] sentry.superuser: superuser.request (url='http://sentry-new.iquality.pro/api/0/internal/mail/' method='POST' ip_address='***REDACTED***' user_id=1)
sentry-web-1  | 16:19:19 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.internal.mail.InternalMailEndpoint' response=500 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/internal/mail/' caller_ip='***REDACTED***' user_agent='Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=50.089428663253784 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-web-1  | 16:19:19 [ERROR] django.request: Internal Server Error: /api/0/internal/mail/ (status_code=500 request=<WSGIRequest: POST '/api/0/internal/mail/'>)
```

The real problem for me is that since access to invite links was removed from UI it is impossible to invite new users without working email setup.

### Expected Result

Sentry is able to send emails over Google's SMTP servers

### Actual Result

Email sending is not working and inviting new users is not possible
