### ISSUE TITLE
What services/pods need access to AWS S3 and SES?

### ISSUE THREAD

**Issue by felipeng** [getsentry/self-hosted#2871]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

N/A

### Docker Compose Version

N/A

### Steps to Reproduce

I am migrating the Sentry configuration from filestore with hardcoded credentials to IRSA, these are my configurations:

`values.yaml`
```
sentry:
  filestore:
    backend: s3
    s3:
      bucketName: sentry
      region_name: us-west-2
      default_acl: private
...
  serviceAccount:
    enabled: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::12345678:role/sentry-test
```

AWS Policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sentry/*",
                "arn:aws:s3:::sentry"
            ],
            "Sid": "AccessToS3"
        },
        {
            "Action": "ses:SendRawEmail",
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "SendEmails"
        }
    ]
}
```

AWS Role -> Trusts Relationship
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::12345678:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/12345678"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/12345678:sub": [
                        "system:serviceaccount:monitoring:sentry-ingest-replay-recordings",
                        "system:serviceaccount:monitoring:sentry-web"
                    ],
                    "oidc.eks.us-west-2.amazonaws.com/id/12345678:aud": "sts.amazonaws.com"
                }
            }
        }
```

So far I only noticed that `sentry-ingest-replay-recordings` and `sentry-web` need access to S3, is there any other pod that need access to S3? 
And for sending email, which pod needs access to SES via IRSA?

### Expected Result

Be able to connect to S3 and SES

### Actual Result

When fail: 
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity`
