### ISSUE TITLE
PostgreSQL unable to do VACUUM

### ISSUE THREAD

**Issue by TheKigen** [getsentry/self-hosted#3234]
### Self-Hosted Version

24.7.1

### CPU Architecture

x86_64

### Docker Version

27.1.0

### Docker Compose Version

2.29.0

### Steps to Reproduce

1. Attempt to run a regular VACUUM on the nodestore table.
```
VACUUM VERBOSE ANALYZE nodestore_node;
```

### Expected Result

Expected the VACUUM would complete.

### Actual Result

The VACUUM errors with something like:
```
could not resize shared memory segment "/PostgreSQL.2058389254" to 67145088 bytes: No space left on device
```

**Comment by TheKigen** [comment]
The fix that I have found is to edit the docker-compose.yml file to add the `shm_size` to a larger size than the docker default.

```
  postgres:
    <<: *restart_policy
    # Using the same postgres version as Sentry dev for consistency purposes
    image: "postgres:14.11"
    shm_size: 1g
```

This issue came about because our nodestore table was absolutely gigantic.  I was attempt to run a normal `VACUUM VERBOSE ANALYZE` against it and it was refusing due to the error.  I assume this issue could have also been preventing the autovacuum from running as well which would explain the size of the table.  It was greater than 500GB.  After making edits, then eventually running `VACUUM FULL` the table reduced to 35GB.
