### ISSUE TITLE
Connection to Kafka with SASL for Sentry containers

### ISSUE THREAD

**Issue by gwyn-bl** [getsentry/self-hosted#3252]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Setup self-hosted Sentry 24.6.0 with external kafka with Sasl auth.

### How are you getting stuck?

Hi! I'm setting self-hosted Sentry 24.6.0 and struggling to config it with Kafka with authentication. Snuba and Relay has no problem with connection, but Sentry services `sentry-subscription-consumer, sentry-ingest-consumer, sentry-worker` giving me this error:

```
6|1723028162.828|FAIL|rdkafka#consumer-1| [thrd:externalKafka.host.io:9093/bootstrap]: externalKafka.host.io:9093/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY, 4 identical error(s) suppressed)
```

Here is configs:
`sentry/sentry.conf.py`

```
DEFAULT_KAFKA_OPTIONS = {
        "bootstrap.servers": externalKafka.host.io:9093,
        "message.max.bytes": 50000000,
        "socket.timeout.ms": 1000,
        "sasl.mechanism": "SCRAM-SHA-512",
        "security.protocol": "SASL_SSL",
        "sasl.username": " ",
        "sasl.password": " ",
    }
```

`relay/config.yml`

```
kafka_config:
        - name: "bootstrap.servers"
          value: "externalKafka.host.io:9093"
        - name: "message.max.bytes"
          value: 50000000
        - name: "sasl.mechanism"
          value: "SCRAM-SHA-512"
        - name: "security.protocol"
          value: "SASL_SSL"
        - name: "sasl.username"
          value: " "
        - name: "sasl.password"
          value: " "
```

Here is the merge which allows SSL for Relay
[Allow enabling SSL for Kafka. (https://github.com/getsentry/relay/pull/3232)](https://github.com/getsentry/relay/releases/tag/24.3.0)

So I assumed that Sentry itself should support it but can't find any examples or docs how to make it work.

Please, tell me what am I doing wrong?

### Where in the product are you?

Unknown

### Version

24.6.0
