### ISSUE TITLE
CA root for smtp not working

### ISSUE THREAD

**Issue by erfantkerfan** [getsentry/self-hosted#3279]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.1.2

### Docker Compose Version

2.29.1

### Steps to Reproduce

1. init a new sentry using official ./install.sh script
2. copy your cert file to certificates directory (I tried both pem and cer extentions in x509 format)
3. set a startlss smtp endpoint with selfsigned certificate
4. send an test email from admin panel

### Expected Result

An email would be sent to reciever.
If even there was on option to not verify validity of tls would be nice.

### Actual Result

my configs:
```yaml
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'mail.company.com'
mail.port: 465
mail.username: 'alert'
mail.password: 'XXXXXXXX'
mail.use-tls: true
# mail.use-ssl: false

mail.from: 'alert@company.com'
```
![Image](https://github.com/user-attachments/assets/3030e626-b608-4db6-866b-eeaef7b7d36f)

![Image](https://github.com/user-attachments/assets/f8c24560-30e6-4c6a-8f73-8cbd2729386a)
