### ISSUE TITLE
24.8.0 When logging in for the first time, click Continue after completing the configuration. 400 error

### ISSUE THREAD

**Issue by haiboer97** [getsentry/self-hosted#3299]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.10

### Docker Compose Version

2.29.2

### Steps to Reproduce

When logging in for the first time, click Continue after completing the configuration. 400 error

/api/0/internal/options/?query=is:required 400 (Bad Request)

### Expected Result

success login

### Actual Result

[WARNING] django.request: Bad Request: /api/0/internal/options/ (status_code=400 request=<WSGIRequest: PUT '/api/0/internal/options/?query=is:required'>)
[WARNING] django.request: Bad Request: /api/0/internal/options/ (status_code=400 request=<WSGIRequest: PUT '/api/0/internal/options/?query=is:required'>)

**Comment by haiboer97** [comment]
![Image](https://github.com/user-attachments/assets/e1a2154d-11a4-4daa-a03b-d6fe4645d12b)

**Comment by aldy505** [comment]
400 means there is a field that you haven't fill in yet. From the screenshot, I can see that you haven't check one of "Send my contact information along with usage statistics" and "Please keep my usage information anonymous". Can you confirm that you've filled every fields?

**Comment by haiboer97** [comment]
I actually tried to check all the options, but the same error message still appeared. However, when I stayed on this page for a while without any operation, I could enter the main interface after refreshing. At this time, I needed to modify ADMIN--》settings--》Usage Statistics to make everything work properly. Otherwise, the error message would still appear when I logged in again next time.

**Comment by kovsienko** [comment]
Self-Hosted Version
24.8.0
24.7.1
CPU Architecture
x86_64

Docker Version
20.10.21

Docker Compose Version
2.29.2

Steps to Reproduce
When logging in for the first time, click Continue after completing the configuration. 400 error

/api/0/internal/options/?query=is:required 400 (Bad Request)

Expected Result
success login

Same problem.
It was resolved in the same way. just wait on the open tab for 10-15 minutes. Then I did as recommended by DMIN--》settings--》Usage Statistics

**Comment by hubertdeng123** [comment]
Interesting, I'm not able to reproduce this issue on my side..

**Comment by jaydrogers** [comment]
I am experiencing this issue too. I am running a brand new configuration of 24.8.0.

I cannot get past this page.

![Image](https://github.com/user-attachments/assets/a30253da-17bd-4d80-a0bd-0ffd128c9519)

**Comment by aldy505** [comment]
> I am experiencing this issue too. I am running a brand new configuration of 24.8.0.
> 
> I cannot get past this page.

@jaydrogers I'm going to try to repro this during the weekend, but a quick question: How did you set things up? Is it just:
```bash
git clone https://github.com/getsentry/self-hosted.git
cd self-hosted
sudo ./install.sh
```

**Comment by jaydrogers** [comment]
Thanks for checking it out. It's basically the steps that I followed other than configuring the sentry configs.

I did put a Traefik container in front of it for automated SSL, but I didn't see any evidence that it was Traefik or CloudFlare causing the issue.

Here is my `docker-compose.overrride.yml`:

```yaml
services:
  nginx:
      ports: []
      labels:
       - "traefik.enable=true"
       - "traefik.docker.network=sentry_onpremise_default"
       - "traefik.http.routers.sentry.rule=Host(`myhost.example.com`)"
       - "traefik.http.routers.sentry.entrypoints=websecure"
       - "traefik.http.routers.sentry.tls=true"
       - "traefik.http.routers.sentry.tls.certresolver=letsencryptresolver"
       - "traefik.http.services.sentry.loadbalancer.server.port=80"
       - "traefik.http.services.sentry.loadbalancer.server.scheme=http"

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    networks:
        - default
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
    logging:
      driver: journald
      options:
        tag: traefik
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik-certificates:/certificates/


networks:
  default:

volumes:
  traefik-certificates:
```

My traefik config was pretty basic other than some CloudFlare configs to restore original IP addresses:
```yaml
# Cloudflare TrustedIPs
x-trustedIps: &trustedIPs
  - "173.245.48.0/20"
  - "103.21.244.0/22"
  - "103.22.200.0/22"
  - "103.31.4.0/22"
  - "141.101.64.0/18"
  - "108.162.192.0/18"
  - "190.93.240.0/20"
  - "188.114.96.0/20"
  - "197.234.240.0/22"
  - "198.41.128.0/17"
  - "162.158.0.0/15"
  - "104.16.0.0/13"
  - "104.24.0.0/14"
  - "172.64.0.0/13"
  - "131.0.72.0/22"
  - "2400:cb00::/32"
  - "2606:4700::/32"
  - "2803:f800::/32"
  - "2405:b500::/32"
  - "2405:8100::/32"
  - "2a06:98c0::/29"
  - "2c0f:f248::/32"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    network: sentry_sentry-self-hosted_default

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
    forwardedHeaders:
      trustedIPs: *trustedIPs
    proxyProtocol:
      trustedIPs: *trustedIPs

  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs: *trustedIPs
    proxyProtocol:
      trustedIPs: *trustedIPs

accessLog: {}
log:
  level: ERROR

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: "myemail@example.com"
      storage: "/certificates/acme.json"
      httpChallenge:
        entryPoint: web
```

### Just a heads up
I did head a different direction than setting up a self-hosted Sentry, but I wanted to share the details of my experience in case it helped others 👍

**Comment by wooch82** [comment]
Hi everyone, I had the same problem for the clean installation and k8s.  Found this error in the console:
![Image](https://github.com/user-attachments/assets/fd807c13-398a-4864-a62a-6eeb1c310e39)
So, I commented a `mail` section in the helm chart, redeployed the chart, and passed this screen without any problems.

**Comment by djooberlee** [comment]
I have the same problem
version 24.9.0

**Comment by aldy505** [comment]
> **UPD: Really!!! after I commented the `mail.use-ssl: false` line in the `sentry/config.yml` file - the problem disappeared**

@djooberlee Just to confirm, does the SMTP server you're using does not use any TLS protocol (no STARTTLS or anything, just plain text)? If that works, maybe we can update the config/documentation about this.

**Comment by djooberlee** [comment]
@aldy505
We use TLS.
Previously, SSL was explicitly listed as disabled, but now I just commented out the line

this is how it looks now
```yaml
mail.backend: 'smtp'
mail.host: 'smtp.example.com'
mail.port: 587
mail.username: 'sender@example.com'
mail.password: 'PASSWORD'
mail.use-tls: True
#mail.use-ssl: false
mail.from: 'sentry@example.com'
mail.enable-replies: False
mail.reply-hostname: ''
```

**Comment by aldy505** [comment]
> [@aldy505](https://github.com/aldy505) We use TLS. Previously, SSL was explicitly listed as disabled, but now I just commented out the line
> 
> this is how it looks now
> 
> mail.backend: 'smtp'
> mail.host: 'smtp.example.com'
> mail.port: 587
> mail.username: 'sender@example.com'
> mail.password: 'PASSWORD'
> mail.use-tls: True
> #mail.use-ssl: false
> mail.from: 'sentry@example.com'
> mail.enable-replies: False
> mail.reply-hostname: ''

Ah I see, I suppose `mail.use-tls` and `mail.use-ssl` is a mutually exclusive configuration? But that's a really good discovery.

**Comment by aldy505** [comment]
It turned out, it is a mutually exclusive configuration:

![Image](https://github.com/user-attachments/assets/41b7cf99-ca18-4355-94b6-4352ec78594a)

See Django's docs: https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-EMAIL_USE_TLS

**Comment by djooberlee** [comment]
It is clear that I cannot set both parameters to TRUE:
```yaml
mail.use-tls: true
mail.use-ssl: true
```
But I never did!!!

And it is not clear to me from the documentation that it is not possible to explicitly set:
```yaml
mail.use-tls: true
mail.use-ssl: false
```
or
```yaml
mail.use-tls: false
mail.use-ssl: true
```

**Comment by aldy505** [comment]
Yeah we need to document this better.

**Comment by vld1234** [comment]
> I am experiencing this issue too. I am running a brand new configuration of 24.8.0.
> 
> I cannot get past this page.
> 
> Note
> 
> I submitted the form with all the fields selected. I just removed my email for the screenshot.
> 
> ![Image](https://github.com/user-attachments/assets/a30253da-17bd-4d80-a0bd-0ffd128c9519)

Have the same issue (App 24.7.1)

**Comment by aldy505** [comment]
@vld1234 Sorry for the very late reply, are you still facing the issue? Or is the workaround works for you?

Also, I've document this: https://github.com/getsentry/self-hosted/pull/3368

**Comment by vld1234** [comment]
> [@vld1234](https://github.com/vld1234) Sorry for the very late reply, are you still facing the issue? Or is the workaround works for you?
> 
> Also, I've document this: [#3368](https://github.com/getsentry/self-hosted/pull/3368)

I've tried with different versions, the same issue.

**Comment by aldy505** [comment]
> > [@vld1234](https://github.com/vld1234) Sorry for the very late reply, are you still facing the issue? Or is the workaround works for you?
> > Also, I've document this: [#3368](https://github.com/getsentry/self-hosted/pull/3368)
> 
> I've tried with different versions, the same issue.

@vld1234 What does your `sentry/config.yml` configuration looks like? Have you make sure that only one of `mail.use-tls` and `mail.use-ssl` uncommented as seen here? https://github.com/getsentry/self-hosted/blob/6a8c3a47587bf23847e51a7de3a21d152f1b7064/sentry/config.example.yml#L15-L18

Also, after changing that configuration file, have you re-run `./install.sh` script?

If that still doesn't help, what kind of workarounds have you tried?

**Comment by gwyn-bl** [comment]
I have the same problem, comment `mail.use-tls` and reinstall doesn't help.

`[WARNING] django.request: Bad Request: /api/0/internal/options/ (status_code=400 request=<WSGIRequest: PUT '/api/0/internal/options/?query=is:required'>)`
![Image](https://github.com/user-attachments/assets/4205b6af-346a-4e64-8e89-983cc95a573c)

I also have another Sentry installation, where both options uncommented and no such problem.

**Comment by hubertdeng123** [comment]
Going to backlog this, thanks

**Comment by gwyn-bl** [comment]
> I have the same problem, comment `mail.use-tls` and reinstall doesn't help.

@hubertdeng123 , sorry for misleading, it was problem with my configuration. My email config was in [sentry.conf.py](https://github.com/sentry-kubernetes/charts/blob/9e95d7b1b18a39b0017355bacce58c2b27655528/charts/sentry/templates/sentry/_helper-sentry.tpl#L564) and even when I commented mail.use-tls there, it somehow getting it anyway, according to logs

```
[INFO] sentry: options.update (ip_address=' ' user_id=1 option_key='mail.use-tls' option_value=False)
[WARNING] django.request: Bad Request: /api/0/internal/options/ (status_code=400 request=<WSGIRequest: PUT '/api/0/internal/options/?query=is:required'>)
```

Moved back email configuration into config.yml and it works.

**Comment by vld1234** [comment]
> > > [@vld1234](https://github.com/vld1234) Sorry for the very late reply, are you still facing the issue? Or is the workaround works for you?
> > > Also, I've document this: [#3368](https://github.com/getsentry/self-hosted/pull/3368)
> > 
> > 
> > I've tried with different versions, the same issue.
> 
> [@vld1234](https://github.com/vld1234) What does your `sentry/config.yml` configuration looks like? Have you make sure that only one of `mail.use-tls` and `mail.use-ssl` uncommented as seen here?
> 
> [self-hosted/sentry/config.example.yml](https://github.com/getsentry/self-hosted/blob/6a8c3a47587bf23847e51a7de3a21d152f1b7064/sentry/config.example.yml#L15-L18)
> 
> Lines 15 to 18 in [6a8c3a4](/getsentry/self-hosted/commit/6a8c3a47587bf23847e51a7de3a21d152f1b7064)
>  # NOTE: `mail.use-tls` and `mail.use-ssl` are mutually exclusive and should not 
>  #        appear at the same time. Only uncomment one of them. 
>  # mail.use-tls: false 
>  # mail.use-ssl: false 
> 
> Also, after changing that configuration file, have you re-run `./install.sh` script?
> 
> If that still doesn't help, what kind of workarounds have you tried?

Hi, it was helm chart.
mail:
  # For example: smtp
  backend: smtp
  useTls: true
  useSsl: false
  username: "WWWW"
  password: "WWWW"
  port: 587
  host: "WWWWW.amazonaws.com"
  from: "wwwwwwwwww.com"

**Comment by vld1234** [comment]
> Also, after changing that configuration file, have you re-run `./install.sh` script?
> 
> If that still doesn't help, what kind of workarounds have you tried?



Hi, it was helm chart:
backend: smtp
useTls: true
useSsl: false
username: ""
password: ""
port: 587
host: "aaaaaaa.amazonaws.com"
from: "aaaaaaa.com"

**Comment by gwyn-bl** [comment]
@vld1234 
> > Also, after changing that configuration file, have you re-run `./install.sh` script?
> > If that still doesn't help, what kind of workarounds have you tried?
> 
> Hi, it was helm chart: backend: smtp useTls: true useSsl: false username: "" password: "" port: 587 host: "aaaaaaa.amazonaws.com" from: "aaaaaaa.com"

Hi, check my answer (they probably answer that they don't support chart). 
Try to move mail config from `sentry.conf.py` to `config.yml`, like in compose installation: https://github.com/getsentry/self-hosted/blob/6a8c3a47587bf23847e51a7de3a21d152f1b7064/sentry/config.example.yml#L10

**Comment by aldy505** [comment]
> > Also, after changing that configuration file, have you re-run `./install.sh` script?
> > If that still doesn't help, what kind of workarounds have you tried?
> 
> Hi, it was helm chart: backend: smtp useTls: true useSsl: false username: "" password: "" port: 587 host: "aaaaaaa.amazonaws.com" from: "aaaaaaa.com"

You have both `useTls` and `useSsl` set. There should be only one of that being set, and the other should be left commented. Please refer to the documentation comment here https://github.com/getsentry/self-hosted/blob/6a8c3a47587bf23847e51a7de3a21d152f1b7064/sentry/config.example.yml#L15-L18

Also yeah, if commenting one of `useTls` or `useSsl` still didn't work, and you've set it on the `config.yml` file and it still didn't work, try to open an issue on the helm chart repo instead.

**Comment by tyr1k** [comment]
> > Also, after changing that configuration file, have you re-run `./install.sh` script?
> > If that still doesn't help, what kind of workarounds have you tried?
> 
> Hi, it was helm chart: backend: smtp useTls: true useSsl: false username: "" password: "" port: 587 host: "aaaaaaa.amazonaws.com" from: "aaaaaaa.com"

Hi! just use default values in chart:
`mail:
  backend: dummy
  useTls: false
  useSsl: false
  username: ""
  password: ""
  port: 25
  host: ""
  from: ""`
 and after succes first install you'll can tap to 'continue' and after do upgrade chart with your config

**Comment by madchap** [comment]
> You have both `useTls` and `useSsl` set. There should be only one of that being set, and the other should be left commented. Please refer to the documentation comment here

Commenting one out will make the helm deployment fail - I just had the issue.

I set it to `true` for both, then afterwards, went back in and set `useSsl` to `false`.

Error from the browser if `useTls: true` and `useSsl: false` on initial installation, will produce a question on the welcome screen which you can then not pass and get the 400 error:

```
{error: "immutable_option", errorDetail: {option: "mail.use-ssl",…}}
error
: 
"immutable_option"
errorDetail
: 
{option: "mail.use-ssl",…}
message
: 
"'mail.use-ssl' cannot be changed at runtime because it is configured on disk"
option
: 
"mail.use-ssl"
```

**Comment by BYK** [comment]
@madchap I think the issue is due to you having both of those variables set (even if one of them is set to `false`). From what I understand from @aldy505's [comment above](https://github.com/getsentry/self-hosted/issues/3299#issuecomment-2484547636), only one of those settings should exist regardless of their value.

All that said, I think we should make the welcome UI handle this issue gracefully, instead of silently failing.

**Comment by madchap** [comment]
> [@madchap](https://github.com/madchap) I think the issue is due to you having both of those variables set (even if one of them is set to `false`). From what I understand from [@aldy505](https://github.com/aldy505)'s [comment above](https://github.com/getsentry/self-hosted/issues/3299#issuecomment-2484547636), only one of those settings should exist regardless of their value.
> 
> All that said, I think we should make the welcome UI handle this issue gracefully, instead of silently failing.

I didn't try to set one to empty, but commenting the `useSsl` altogether in the case of sentry-kubernetes made the deployment fail. Possibly not a problem with your project then, but with the other. Cheers @BYK and happy new year.

**Comment by LvckyAPI** [comment]
same issue on v24.12.1 using reverse proxy (traefik)

**Comment by LvckyAPI** [comment]
From Browser Console: 

```json
{
    "error": "immutable_option",
    "errorDetail": {
        "option": "mail.use-tls",
        "message": "'mail.use-tls' cannot be changed at runtime because it is configured on disk"
    }
}
```

Settings:
![Image](https://github.com/user-attachments/assets/014a3e93-4d66-4597-b67d-49924ae3dd4b)

**Comment by LvckyAPI** [comment]
Disabling BOTH options like:

```yaml
# NOTE: `mail.use-tls` and `mail.use-ssl` are mutually exclusive and should not
#        appear at the same time. Only uncomment one of them.
#mail.use-tls: false
#mail.use-ssl: false
```

does work.

After disabling both, i can submit the settings

**Comment by etowett** [comment]
Found myself experiencing the same thing

<img width="1021" alt="Image" src="https://github.com/user-attachments/assets/55891e13-12c9-47af-b96d-6e94d5f46462" />

I reconstructed the same request using curl, copying values from network tab of my browser

```
curl -X PUT https://sentry.example.co/api/0/internal/options/?query=is:required \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Cookie: perf_dv6Tr4n=1; sudo=ILWKe98oRcj1:1tYSWi:gNhU_V0_YxWfmdH7UeDjs2owk_C2pZqSIP3wshoYwVk; sc=syB4p9IjoKM9dJ55dy99J49w6qqCjfZK; su=qA2SEMyNMoBl:1tYSYr:h9u86R63jOggBrEUfZNKjKoVo2TcrgSgt3Wf0mVLxpc; sentrysid=.eJxVj70OgjAUhd-lsyGl9EJhw8TBKA46OJL2tgQURSlNNIZ3txhMdLv5zk_OfZFSuqEunTV92WiSkZAsfpmSeDbXSbDmOvTPwA1Na4PJEKwusmlzfy1n01-ylrb2MQTBTcSUQRUpkwpaUawAK8GkFsgFpEqHECMTEbJEI8g4xVBTHQPlFUyl1unON623x40v6PZ4-oy0jmQvYh63aXUSJRQEMO6VRrdfxCGExKOhO3t0z9lhVTx3RbdsPXTzw-P4BnukUGY:1tYSYr:BDgLxzhP2tgGUejupRIOMaEFINFtqT0cgx0LoGF-404" \
  -H "x-csrftoken: syB4p9IjoKM9dJ55dy99J49w6qqCjfZK" \
  -H "Referer: https://sentry.example.co/organizations/new/" \
  -d '{
    "system.admin-email":"admin@example.com",
    "auth.allow-registration":false,
    "beacon.record_cpu_ram_usage":"true",
    "beacon.anonymous":"false"
  }'
```

**Comment by prasadkris** [comment]
I am getting the same error with Sentry version 24.12.2. We don’t have a full-fledged SMTP server; instead, we use a relay server that does not require a username or password. Below are the mail settings for our self-hosted deployment on Kubernetes, using the Sentry Helm chart.

```
mail:
  backend: smtp
  from: "noreply@xxxxx.dev"
  host: "gateway.xxxxx.com"
  password: ""
  port: 25
  useSsl: false
  useTls: false
  username: ""
```

I have tried removed the `useSsl` / `useTls` options, but I get the following error when logging in for the first time.

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/2b35ba89-b125-48bf-93ff-82619a7beea4" />

Does this mean Sentry no longer supports mail servers without authentication? The sending mail option doesn't seem to work if I exclude the username and password fields. Any thoughts? Thanks.
