### ISSUE TITLE
Add Uptime Monitoring

### ISSUE THREAD

**Issue by aldy505** [getsentry/self-hosted#3304]
### Problem Statement

Uptime Monitoring feature is out and it's on Early Release. We should bring that here if it hits General Availability.

Product discussion: https://github.com/getsentry/sentry/discussions/51110
Announcement: https://sentry.io/changelog/uptime-monitoring-early-adopters-release/
Documentation: https://docs.sentry.io/product/alerts/uptime-monitoring/

### Solution Brainstorm

The way we'll tell you how to configure this should be versioned (learned this the hard way from User Feedback feature). Grab the version you're currently on (or if yours is higher than any of these, choose the highest one).

- Setup guide for 24.8.0

**Comment by aldy505** [comment]
## Setup guide for 24.8.0

Date of writing: 2024-08-31

Does this works for versions below 24.8.0? I have no idea.

On your `docker-compose.yml`, add a few new containers:
```yaml
  uptime-results:
    <<: *sentry_defaults
    command: run consumer uptime-results --consumer-group uptime-results
    profiles:
      - feature-complete
  uptime-checker:
    <<: *restart_policy
    # IMPORTANT, READ THIS!
    # If you trust me enough (although we probably never met), you can use the Docker image I built to save some time, so you can use this:
    # image: "aldy505/sentry-uptime-checker:8ffa29b89b319e4b8e51154e82569796ea74c3af"
    #
    # But if you don't trust me enough and prefer to build from source yourself, use this instead (I'm using this on my instance).
    # If you're using the `image` section above, obviously you'll need to remove this `build` section (or just comment it out).
    build: ./uptime-checker-git
    command: run --config /config.yml
    volumes:
      - type: bind
        read_only: true
        source: ./uptime-checker/config.yml
        target: /config.yml
    depends_on:
      kafka:
        <<: *depends_on-healthy
      redis:
        <<: *depends_on-healthy
    profiles:
      - feature-complete
```

On your `sentry/sentry.conf.py`, add some new feature flags:
```python
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
          # The rest of your features
        )
        # Uptime Monitoring related flags
        + (
            "organizations:uptime-api-create-update",
            "organizations:uptime-automatic-hostname-detection",
            "organizations:uptime-automatic-subscription-creation",
            "organizations:uptime-rule-api",
            "organizations:uptime-create-issues",
            "organizations:uptime-settings",
            "organizations:uptime-visible", # This is for issues platform
            "organizations:uptime-ingest",
            "organizations:uptime-post-process-group",
        )
    }
)
```

Create a new directory called `uptime-checker`, create a `config.yml` file. The resulting path is `uptime-checker/config.yml`:
```yaml
# See https://github.com/getsentry/uptime-checker/blob/8ffa29b89b319e4b8e51154e82569796ea74c3af/src/app/config.rs
# You could technically use environment variable instead of this file, if you prefer, but I think it's better to use this instead.
# If you really want to use environment variables, do something like: UPTIME_CHECKER_SENTRY_DSN UPTIME_CHECKER_REDIS_HOST, you know the rest.

# sentry_dsn: <string, optional>
# sentry_env: <string, optional>
log_level: error # valid values: off, trace, debug, info, warn, error
log_format: auto # valid values: auto, pretty, simplified, json

checker_concurrency: 200

results_kafka_cluster: "kafka:9092"
results_kafka_topic: "uptime-results"
configs_kafka_cluster: "kafka:9092"
configs_kafka_topic: "uptime-configs"

redis_host: "redis://redis:6379"
```

If on the `docker-compose.yml` file you're not using the Docker image that I built, add a line on `install.sh`:
```bash
# ...
source install/update-docker-images.sh
source install/build-uptime-checker.sh # Add this (also remove this comment)
source install/build-docker-images.sh
# ...
```
And create the file `install/build-uptime-checker.sh` (still if you're not using the Docker image that I built):
```bash
echo "${_group}Building uptime-checker ... "

rm -rf uptime-checker-git

git clone --depth 1 https://github.com/getsentry/uptime-checker.git uptime-checker-git

echo "${_endgroup}"
```

After all that, run the `./install.sh` script. Good luck.

**Comment by internal-keydev** [comment]
Is there a setup guide for 24.10.0?

**Comment by aldy505** [comment]
@evanpurkhiser @wedamija Hey, someone on Discord (link: https://discord.com/channels/621778831602221064/1320980341061849109) reported that no issues are registered when the server is down, they have set up the alerts for uptime checker. They're building the Docker image from source. Is there anything that's missing from my setup/config above?

![Image](https://github.com/user-attachments/assets/0c5b1ace-10c1-45a9-89f8-27bf9ab5903d)

**Comment by aldy505** [comment]
## Setup Guide for 25.1.0

Date of writing: 2025-01-16

Add some new containers on your `docker-compose.yml`:
```yaml
  uptime-checker:
    <<: *restart_policy
    image: "$UPTIME_IMAGE"
    command: run
    environment:
      UPTIME_CHECKER_SENTRY_DSN: "$SENTRY_DSN"
      UPTIME_CHECKER_RESULTS_KAFKA_CLUSTER: kafka:9092
      UPTIME_CHECKER_RESULTS_KAFKA_TOPIC: uptime-results
      UPTIME_CHECKER_CONFIGS_KAFKA_CLUSTER: kafka:9092
      UPTIME_CHECKER_CONFIGS_KAFKA_TOPIC: uptime-configs
      UPTIME_CHECKER_REDIS_HOST: redis://redis:6379
      UPTIME_CHECKER_LOG_LEVEL: debug # Valid options: info, warn, error, debug
    depends_on:
      kafka:
        <<: *depends_on-healthy
      redis:
        <<: *depends_on-healthy
    profiles:
      - feature-complete
  uptime-results:
    <<: *sentry_defaults
    command: run consumer uptime-results --consumer-group uptime-results
    profiles:
      - feature-complete
  snuba-uptime-results-consumer:
    <<: *snuba_defaults
    command: rust-consumer --storage uptime_monitor_checks --consumer-group snuba-uptime-results --auto-offset-reset=latest --max-batch-time-ms 750 --no-strict-offset-reset
    profiles:
      - feature-complete
```

For `snuba-uptime-results-consumer` if you have problem with `rust-consumer` just use regular Python `consumer`.

On your `.env` or `.env.custom` file, just add this:
```bash
UPTIME_IMAGE=aldy505/sentry-uptime-checker:latest
```

To be honest, I'm tired of having the install script that builds the Docker image locally, so I'll just build this regularly every release (or every time I do upgrades).

Then on your `sentry/sentry.conf.py` add these feature flags:
```py
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            # ... the original feature flags
        )
        # Uptime Monitoring related flags
        + (
            "organizations:uptime-automatic-hostname-detection",
            "organizations:uptime-automatic-subscription-creation",
            "organizations:uptime-create-issues",
            "organizations:uptime-settings",
            "organizations:uptime-visible", # For issues platform, I don't know if this is still required
            "organizations:uptime-ingest",
            "organizations:uptime-post-process-group",
            "organizations:insights-uptime", # Enables `Uptime` section on the web UI, but this don't really works, you can't access it.
        )
    }
)
```

After all that, re run `./install.sh` script.

**Comment by aldy505** [comment]
## Setup Guide for 25.2.0

Date of writing: 2025-01-24

At the time of this writing, 25.2.0 hasn't been released yet. So please re-check or ping me on Discord if you're not sure.

The same as 25.1.0, but for allow internal IPs:

### Allow Internal IPs

Just add an environment variable on your Docker Compose:
```yaml
UPTIME_CHECKER_ALLOW_INTERNAL_IPS: true
```

**Comment by aldy505** [comment]
## Setup Guide for 25.3.0

Date of writing: 2025-03-18

If you're using custom CA certificate or self-signed TLS certificate, read until the end, don't waste your time by executing `install.sh` multiple times.

Modify your Docker Compose file:
```yaml
  uptime-checker:
    <<: *restart_policy
    image: "$UPTIME_IMAGE"
    command: run
    environment:
      UPTIME_CHECKER_SENTRY_DSN: "$SENTRY_DSN" # Set this to your internal SENTRY_DSN to monitor this container
      UPTIME_CHECKER_RESULTS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_CONFIGS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_REDIS_HOST: "redis://redis:6379"
      UPTIME_CHECKER_LOG_LEVEL: "debug" # Valid options: info, warn, error, debug
      # Allow uptime checks against internal IP addresses
      UPTIME_CHECKER_ALLOW_INTERNAL_IPS: true
      # If you are using statsd to monitor metrics and stuff, you can uncomment this:
      #UPTIME_CHECKER_STATSD_ADDR: "127.0.0.1:8125"
      # If you want to enable HTTP connection reuse to save up connection time, you can set this to true, otherwise, just comment it out:
      #UPTIME_CHECKER_DISABLE_CONNECTION_REUSE: true
      # Sets the maximum time in seconds to keep idle sockets alive in the http checker.
      #UPTIME_CHECKER_POOL_IDLE_TIMEOUT_SECS: 300
      # The number of times to retry failed checks before reporting them as failed
      #UPTIME_CHECKER_FAILURE_RETRIES: 5
    depends_on:
      kafka:
        <<: *depends_on-healthy
      redis:
        <<: *depends_on-healthy
    profiles:
      - feature-complete
  uptime-results:
    <<: *sentry_defaults
    command: run consumer uptime-results --consumer-group uptime-results
    profiles:
      - feature-complete
  snuba-uptime-results-consumer:
    <<: *snuba_defaults
    command: rust-consumer --storage uptime_monitor_checks --consumer-group snuba-uptime-results --auto-offset-reset=latest --max-batch-time-ms 750 --no-strict-offset-reset
    profiles:
      - feature-complete
```

On your `.env` file (or `.env.custom`), add this:
```bash
UPTIME_IMAGE=aldy505/sentry-uptime-checker:b238224f70e23267febdd4100f02068cb2ba18bc
```

On your `sentry/sentry.conf.py`, update your feature flags:
```python
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            # ... the original feature flags
        )
        # Uptime Monitoring related flags
        + (
            "organizations:uptime",
            "organizations:insights-uptime", # Enable access to insights uptime view
            "organizations:uptime-automatic-hostname-detection",
            "organizations:uptime-automatic-subscription-creation",
            "organizations:uptime-create-issues", # Enable creating issues via the issue platform
            "organizations:uptime-settings", # Enables uptime related settings for projects and orgs
            # Below these are for issues platform
            "organizations:uptime-domain-failure-visible",
            "organizations:uptime-domain-failure-ingest",
            "organizations:uptime-domain-failure-post-process-group",
        )
    }
)
```

On your `sentry/config.yml`, add this line on the very bottom:
```yaml
uptime.snuba_uptime_results.enabled: true
```

Then, run `./install.sh` script and you're done.

Just trust me on that image, you can also build it yourself but why even bother. I provide both linux/amd64 and linux/arm64 image. Here's how I build it for future reference (which probably just for me):
```bash
sudo docker buildx build --platform linux/arm64,linux/amd64 --tag "aldy505/sentry-uptime-checker:$(git log -1 --format=%H | xargs)" . && \
sudo docker image tag "aldy505/sentry-uptime-checker:$(git log -1 --format=%H | xargs)" "aldy505/sentry-uptime-checker:latest" && \
sudo docker image push "aldy505/sentry-uptime-checker" --all-tags
```

### Custom CA Certificates

If your URL contains self-signed TLS certificate, you should do some modifications after applying all that above. Store your CA certificates on the certificates directory (the directory already exists, with gitignore in it). 

On your `docker-compose.yml` file, modify `uptime-checker` like so:
```yaml
  uptime-checker:
    <<: *restart_policy
    image: uptime-checker-local
    build:
      context: .
      dockerfile: ./uptime-checker/Dockerfile
      args:
        - UPTIME_IMAGE
    command: run
    environment:
      UPTIME_CHECKER_SENTRY_DSN: "$SENTRY_DSN" # Set this to your internal SENTRY_DSN to monitor this container
      UPTIME_CHECKER_RESULTS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_CONFIGS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_REDIS_HOST: "redis://redis:6379"
      UPTIME_CHECKER_LOG_LEVEL: "debug" # Valid options: info, warn, error, debug
      # Allow uptime checks against internal IP addresses
      UPTIME_CHECKER_ALLOW_INTERNAL_IPS: true
      # If you are using statsd to monitor metrics and stuff, you can uncomment this:
      #UPTIME_CHECKER_STATSD_ADDR: "127.0.0.1:8125"
      # If you want to enable HTTP connection reuse to save up connection time, you can set this to true, otherwise, just comment it out:
      #UPTIME_CHECKER_DISABLE_CONNECTION_REUSE: true
      # Sets the maximum time in seconds to keep idle sockets alive in the http checker.
      #UPTIME_CHECKER_POOL_IDLE_TIMEOUT_SECS: 300
      # The number of times to retry failed checks before reporting them as failed
      #UPTIME_CHECKER_FAILURE_RETRIES: 5
    volumes:
      - ./certificates:/ca-certificates:ro # This!
    depends_on:
      kafka:
        <<: *depends_on-healthy
      redis:
        <<: *depends_on-healthy
    profiles:
      - feature-complete
```

Create a directory `uptime-checker`, create a file `Dockerfile` inside it. On your `uptime-checker/Dockerfile`, put this:
```dockerfile
ARG UPTIME_IMAGE
FROM ${UPTIME_IMAGE}

USER root
COPY ./certificates /ca-certificates
RUN cat /ca-certificates/* >> /etc/ssl/certs/ca-certificates.crt
USER app
```

**Comment by aldy505** [comment]
## Setup Guide for 25.4.0

Date of writing: 2025-04-17

> [!NOTE]
> Changes from previous version (25.3.0):
> 1. I do have lots of uptime monitor, having it to use the same redis with `relay` and `sentry` containers really caused issues. It kinda make it lags for some unknown reasons. Therefore, on this version, I'd prefer to have a separate Redis instance.
> 2. The `log level: debug` is causing storage issues, therefore you should try to set it as `warn` instead. See https://github.com/getsentry/self-hosted/issues/3648

If you're using custom CA certificate or self-signed TLS certificate, read until the end, don't waste your time by executing `install.sh` multiple times.

Modify your Docker Compose file:
```yaml
  uptime-redis:
    <<: *restart_policy
    image: "redis:6.2.14-alpine"
    healthcheck:
      <<: *healthcheck_defaults
      test: redis-cli ping | grep PONG
    volumes:
      - "sentry-uptime-redis:/data"
      - type: bind
        read_only: true
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 10032
        hard: 10032
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  uptime-checker:
    <<: *restart_policy
    image: "$UPTIME_IMAGE"
    command: run
    environment:
      UPTIME_CHECKER_SENTRY_DSN: "$SENTRY_DSN" # Set this to your internal SENTRY_DSN to monitor this container
      UPTIME_CHECKER_RESULTS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_CONFIGS_KAFKA_CLUSTER: "kafka:9092"
      UPTIME_CHECKER_REDIS_HOST: "redis://uptime-redis:6379"
      # BEWARE! This will spam lots of stuff and cause storage problems. You might want to change this to "warn" instead.
      UPTIME_CHECKER_LOG_LEVEL: "debug" # Valid options: info, warn, error, debug
      # Allow uptime checks against internal IP addresses
      UPTIME_CHECKER_ALLOW_INTERNAL_IPS: true
      # If you are using statsd to monitor metrics and stuff, you can uncomment this:
      #UPTIME_CHECKER_STATSD_ADDR: "127.0.0.1:8125"
      # If you want to enable HTTP connection reuse to save up connection time, you can set this to true, otherwise, just comment it out:
      #UPTIME_CHECKER_DISABLE_CONNECTION_REUSE: true
      # Sets the maximum time in seconds to keep idle sockets alive in the http checker.
      #UPTIME_CHECKER_POOL_IDLE_TIMEOUT_SECS: 300
      # The number of times to retry failed checks before reporting them as failed
      #UPTIME_CHECKER_FAILURE_RETRIES: 5
      # DNS name servers to use when making checks in the http checker
      #UPTIME_CHECKER_HTTP_CHECKER_DNS_NAMESERVERS: "8.8.8.8,8.8.4.4"
    depends_on:
      kafka:
        <<: *depends_on-healthy
      uptime-redis:
        <<: *depends_on-healthy
    profiles:
      - feature-complete
  uptime-results:
    <<: *sentry_defaults
    command: run consumer uptime-results --consumer-group uptime-results
    profiles:
      - feature-complete
  snuba-uptime-results-consumer:
    <<: *snuba_defaults
    command: rust-consumer --storage uptime_monitor_checks --consumer-group snuba-uptime-results --auto-offset-reset=latest --max-batch-time-ms 750 --no-strict-offset-reset
    profiles:
      - feature-complete

# scroll down...
volumes:
  # every other volumes
  sentry-uptime-redis: # yep, just this one line
```

On your `.env` file (or `.env.custom`), add this:
```bash
UPTIME_IMAGE=aldy505/sentry-uptime-checker:7f7a88d7b5094a6f830e06232a03ee52733ed796
```

On your `sentry/sentry.conf.py`, update your feature flags:
```python
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            # ... the original feature flags
        )
        # Uptime Monitoring related flags
        + (
            "organizations:uptime",
            "organizations:insights-uptime", # Enable access to insights uptime view
            "organizations:uptime-automatic-hostname-detection",
            "organizations:uptime-automatic-subscription-creation",
            "organizations:uptime-create-issues", # Enable creating issues via the issue platform
            "organizations:uptime-settings", # Enables uptime related settings for projects and orgs
            # Below these are for issues platform
            "organizations:uptime-domain-failure-visible",
            "organizations:uptime-domain-failure-ingest",
            "organizations:uptime-domain-failure-post-process-group",
        )
    }
)

# Also add this to make sure that it really works
SENTRY_USE_UPTIME = True
```

On your `sentry/config.yml`, add this line on the very bottom:
```yaml
uptime.snuba_uptime_results.enabled: true
```

Then, run `./install.sh` script and you're done.

Just trust me on that image, you can also build it yourself but why even bother. I provide both linux/amd64 and linux/arm64 image. Here's how I build it for future reference (which probably just for me):
```bash
sudo docker buildx build --platform linux/arm64,linux/amd64 --tag "aldy505/sentry-uptime-checker:$(git log -1 --format=%H | xargs)" . && \
sudo docker image tag "aldy505/sentry-uptime-checker:$(git log -1 --format=%H | xargs)" "aldy505/sentry-uptime-checker:latest" && \
sudo docker image push "aldy505/sentry-uptime-checker" --all-tags
```

### Custom CA Certificates

If your URL contains self-signed TLS certificate, you should do some modifications after applying all that above. Store your CA certificates on the certificates directory (the directory already exists, with gitignore in it). 

On your `docker-compose.yml` file, modify `uptime-checker` like so (everything else is the same as the one I defined on the top, just modify these specific keys):
```yaml
  uptime-checker:
    image: uptime-checker-local
    build:
      context: .
      dockerfile: ./uptime-checker/Dockerfile
      args:
        - UPTIME_IMAGE
    volumes:
      - ./certificates:/ca-certificates:ro # This!
```

Create a directory `uptime-checker`, create a file `Dockerfile` inside it. On your `uptime-checker/Dockerfile`, put this:
```dockerfile
ARG UPTIME_IMAGE
FROM ${UPTIME_IMAGE}

USER root
COPY ./certificates /ca-certificates
RUN cat /ca-certificates/* >> /etc/ssl/certs/ca-certificates.crt
USER app
```
