### ISSUE TITLE
Release file cleanup and standardisation

### ISSUE THREAD

**Issue by sree-warrier** [getsentry/self-hosted#3334]
### Problem Statement

Where the release files are stored (Assuming it to the filestore(disk/buckets), please do correct if its are wrong) ?
How the release files are been cleaned ? While checking we found that with the retention we set is not doing the cleanup activity with releases. Any configuration referring to the release retentions ? Any standard practice to follow on release file maintenance, as its filling the disk. 

### Solution Brainstorm

NA

**Comment by bijancot** [comment]
Hi,

Do you have any information which services/container that data filling up your disk? Long time ago i have issue with the postgresql even after execute cleanup manually. It turns out in my case i need to also do a vacuum in purpose to reclaim the disk. 

and if you want to set the retention period you can take a look at `.env` https://github.com/getsentry/self-hosted/blob/master/.env#L3 but you need to rerun install process and` docker compose up` i think for better result 

Cheers 
Baskoro

**Comment by webard** [comment]
Look at this issue https://github.com/getsentry/self-hosted/issues/2313

Make `docker-compose.override.yml` with content below:
```
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  disk-cleanup:
    <<: *restart_policy
    image: sentry-cleanup-self-hosted-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: sentry-self-hosted-local
    entrypoint: "/entrypoint.sh"
    command: '"0 0 * * * find /_data/files -type d -empty | xargs -r rmdir"'
    volumes:
      - sentry-data:/_data

  disk-cleanup-files:
    <<: *restart_policy
    image: sentry-cleanup-self-hosted-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: sentry-self-hosted-local
    entrypoint: "/entrypoint.sh"
    environment:
      # Leaving the value empty to just pass whatever is set
      # on the host system (or in the .env file)
      SENTRY_EVENT_RETENTION_DAYS:
    command: '"0 30 * * * find /_data/files -type f -atime +$SENTRY_EVENT_RETENTION_DAYS -delete"'
    volumes:
      - sentry-data:/_data
 ```

and run `./install.sh` to install new services. They will clean outdated files and empty directories every day. You can also manually run commands from services to see effects immediately.
