### ISSUE TITLE
How do I change the ClickHouse address to an external server's address?

### ISSUE THREAD

**Issue by ZLBillShaw** [getsentry/self-hosted#3339]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

1.29.2

### Steps to Reproduce

How do I change the ClickHouse address to an external server's address?

I tried adding the following to the .env file:

SENTRY_CLICKHOUSE_HOST=xx  
SENTRY_CLICKHOUSE_PORT=9000  
SENTRY_CLICKHOUSE_USER=xxx  
SENTRY_CLICKHOUSE_PASSWORD=xxx  
SENTRY_CLICKHOUSE_DATABASE=sentry  

It doesn't seem to take effect.

### Expected Result

 I hope to see the relevant information in the ClickHouse database.

### Actual Result

But in fact, I do not see any relevant information.

**Comment by aldy505** [comment]
Modify this section https://github.com/getsentry/self-hosted/blob/5bd6cd3710cc214b2d68858d24a7d6bcf8149d73/docker-compose.yml#L78-L87

Into:
```yaml
  environment:
    SNUBA_SETTINGS: self_hosted
    CLICKHOUSE_HOST:
    CLICKHOUSE_PORT:
    CLICKHOUSE_USER:
    CLICKHOUSE_PASSWORD:
    CLICKHOUSE_DATABASE:
    CLICKHOUSE_HTTP_PORT:
    DEFAULT_BROKERS: "kafka:9092"
    REDIS_HOST: redis
    UWSGI_MAX_REQUESTS: "10000"
    UWSGI_DISABLE_LOGGING: "true"
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    SENTRY_EVENT_RETENTION_DAYS:
```

Then on your `.env` (or `.env.custom` if you have any), fill those new environment vars with your config. This config assume you're running a single node ClickHouse with no Zookeeper (also assumes you're running ClickHouse Keeper if any). The snuba config is here: https://github.com/getsentry/snuba/blob/bfffbd611db840824c5a65c9bf71493374cbceec/snuba/settings/__init__.py#L81-L138

If you want to use a ClickHouse cluster, I don't think I can really help you with that, as I don't see any way to configure the connection as cluster. You'll need to browse the `snuba` repository for that.
