### ISSUE TITLE
How to scale ingest-replay-recordings consumer?

### ISSUE THREAD

**Issue by 2snEM6** [getsentry/self-hosted#3428]
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

27.3.1

### Docker Compose Version

2.29.7

### Steps to Reproduce

I'm trying to scale `ingest-replay-recordings` to multiple replicas because we have a big amount of replays coming to our server.

I scaled the number of replicas to `3` in the docker-compose:

```
  ingest-replay-recordings:
    <<: *sentry_defaults
    command: run consumer ingest-replay-recordings --consumer-group ingest-replay-recordings
    profiles:
      - feature-complete
    deploy:
      replicas: 3
```

And I increased the number of Kafka partitions for the topic:

```docker-compose exec kafka kafka-topics --alter --topic ingest-replay-recordings --partitions <number_of_partitions> --bootstrap-server kafka:9092```

This works, and it seems all three replicas have partitions and are receiving `ingest-replay-recordings` events.

However, in our particular case, the majority of replay ingestion events from from a single project, and AFAIK, events are grouped per project per consumer, so, one of the tree consumers is still overloaded with events.

How can I do to allow distribution of events across all  `ingest-replay-recordings` consumers?

Thank you!

### Expected Result

.

### Actual Result

.
