### ISSUE TITLE
when filesystem migration to s3, /api/repplay error 502

### ISSUE THREAD

**Issue by vaynevayne** [getsentry/self-hosted#3438]
my step is 
```jsx 
docker compose down
// edit sentry/config.yml
docker compose --env-file .env.custom up
```
some times 
```jsx 
docker compose down
// edit sentry/config.yml
./install.sh
```

problem : replay menu  has red error alert  and `/api/replay`   response  http code 502

### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

26.1.4

### Docker Compose Version

2.27.1

### Steps to Reproduce

```yml
filestore.backend: 'filesystem'
filestore.options:
  location: '/data/files'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'

# filestore.backend: 's3'
# filestore.options:
#   access_key: 'AKIXXXXXX'
#   secret_key: 'XXXXXXX'
#   bucket_name: 's3-bucket-name'

```

replace to 

```yml
# filestore.backend: 'filesystem'
# filestore.options:
#   location: '/data/files'
# dsym.cache-path: '/data/dsym-cache'
# releasefile.cache-path: '/data/releasefile-cache'


filestore.backend: "s3"
filestore.options:
  bucket_acl: "private"
  default_acl: "private"
  access_key: "****"
  secret_key: "****"
  bucket_name: "my-bucket"
  region_name: "auto"
  endpoint_url: "http://******.net" # If you're not using AWS.
  addressing_style: "auto" # For regular AWS S3, use "auto" or "virtual". For other S3-compatible API like MinIO or Ceph, use "path".
  signature_version: "s3v4"
```

### Expected Result

work well 

### Actual Result

replay ui  with red  error 
replay api throw 502 

then  i clearup data, recreate admin account,   replay ui is ok, and send a replay by feedback,  but can't show any replay or feedback
![Image](https://github.com/user-attachments/assets/761c5984-5b29-4852-8012-1d98e197fc43)
