### ISSUE TITLE
Source maps are not being applied to issues

### ISSUE THREAD

**Issue by NgLoader** [getsentry/self-hosted#3671]
### Self-Hosted Version

25.4.0 a00823c

### CPU Architecture

x86_64

### Docker Version

28.1.1, build 4eba377

### Docker Compose Version

2.35.1

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

Setup:
- Angular (19.2.2) with Ionic (8.5.0) and Capacitorjs (7.0.0)
- Sentry capacitor [1.2.0](https://github.com/getsentry/sentry-capacitor/releases/tag/1.2.0)

1. Set up Sentry code mappings inside GitHub Actions
```yaml
- name: Install Sentry CLI
  run: npm i -g @sentry/cli --unsafe-perm

- name: Sentry upload sourcemaps
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: "" #e.g example-company
    SENTRY_PROJECT: "" #e.g example-app
    RELEASE_VERSION: ${{ needs.setup.outputs.version }} #e.g. 1.2.7
    DIST_VERSION: ${{ needs.setup.outputs.dist }} #e.g. 184-319e204
    ENVIRONMENT_TYPE: ${{ needs.setup.outputs.environment }} #e.g. production
  run: |
    npx sentry-cli releases new "$RELEASE_VERSION"
    npx sentry-cli releases set-commits --auto "$RELEASE_VERSION"
    npx sentry-cli releases files "$RELEASE_VERSION" upload-sourcemaps ./www/browser --dist $DIST_VERSION --rewrite
    npx sentry-cli releases finalize "$RELEASE_VERSION"
    npx sentry-cli releases deploys "$RELEASE_VERSION" new -e $ENVIRONMENT_TYPE

- name: Delete sourcemaps
  run: find ./www/browser -name "*.map" -type f -delete
```

2. Setup app
```js
Sentry.init({
  dsn: isAppMode()
    ? AppConstants.URL_SENTRY_APP
    : AppConstants.URL_SENTRY_WEB,
  release: environment.version, //e.g. 1.2.7
  environment: environment.environment, //e.g. production
  dist: environment.dist, //e.g. 184-319e204

  enabled: !isDevMode(),
  sendDefaultPii: false,
  enableNative: true,
  enableNativeCrashHandling: true,
  enableNativeNagger: true,
  enableTracing: true,
  enableNdkScopeSync: true,
  enableAppHangTracking: true,
  enableAutoSessionTracking: true,
  enableCaptureFailedRequests: true,
  enableWatchdogTerminationTracking: true,

  transport: SentryAngular.makeBrowserOfflineTransport(SentryAngular.makeFetchTransport),

  integrations: [
    SentryAngular.browserTracingIntegration(),
    SentryAngular.browserProfilingIntegration(),
    SentryAngular.browserApiErrorsIntegration(),
    SentryAngular.feedbackIntegration({
      autoInject: false
    }),
    SentryAngular.breadcrumbsIntegration(),
    SentryAngular.extraErrorDataIntegration(),
    SentryAngular.linkedErrorsIntegration(),
    SentryAngular.captureConsoleIntegration({
      levels: ['error']
    }),
    SentryAngular.replayIntegration({
      maskAllText: true,
      maskAllInputs: true,
      blockAllMedia: true
    })
  ],

  // Fix: https://sentry.zendesk.com/hc/en-us/articles/26649121915291-I-m-getting-Object-captured-as-exception-with-keys
  // Issue: https://github.com/getsentry/sentry-javascript/issues/2292
  ignoreErrors: ['Object captured as exception'],

  sampleRate: 1,

  tracesSampleRate: 1,
  tracePropagationTargets: ['test.example.app', 'localhost'],

  // Session Replay
  replaysSessionSampleRate: isDevMode() ? 1 : 0.1,
  replaysOnErrorSampleRate: 1.0,

  profilesSampleRate: 1,

  // Forward the init method from @sentry/angular-ivy
  SentryAngular.init
});
```

3. Throw an app error
4. The reference couldn't be found

<img width="512" alt="Image" src="https://github.com/user-attachments/assets/62e3ea37-cae7-4cf0-8797-4bedfe435a7d" />

### Expected Result

Resolve the correct source mappings

### Actual Result

When I open the source map myself im able to find the correct place.

<img width="525" alt="Image" src="https://github.com/user-attachments/assets/154b0cce-cbf2-4bb5-a688-53c8a2acef8d" />

<img width="594" alt="Image" src="https://github.com/user-attachments/assets/45d626ff-53e8-4d35-9b95-0eac07b13de5" />

<img width="960" alt="Image" src="https://github.com/user-attachments/assets/ab287b79-4967-469e-9441-2c813ea673b6" />

[sentry_install_log-2025-04-21_20-07-44.txt](https://github.com/user-attachments/files/19840901/sentry_install_log-2025-04-21_20-07-44.txt)
