### ISSUE TITLE
Let port binding management to docker-compose.override.yml instead of variable usage

### ISSUE THREAD

**Issue by soullivaneuh** [getsentry/self-hosted#694]
## Summary

Port binding of the nginx server is currently defined with a env variable: https://github.com/getsentry/onpremise/blob/ae9378862caead70b620bb347bf5510833889478/docker-compose.yml#L199-L200

Instead, we should remove the port binding completely and let the user set it up on `docker-compose.override.yml` like this:

```yaml
version: '3.4'

services:
  nginx:
    ports:
      - 80 # Do whatever you want here.
```

## Motivation

Because of a [lack of functionnality of docker-compose](https://github.com/docker/compose/issues/3729) we are currently not able to **remove** the port binding.

As you [suggested on your documentation](https://github.com/getsentry/onpremise#securing-sentry-with-ssltls) I would like to setup a reverse proxy by adding a Traefik router service on the docker stack.

In that case, I do not want to expose the nginx port directly for security reason and because it will become totally useless.

I technically can not do that expect if I modify your `docker-compose.yml` directly, but this is not the proper way and I will always have a git diff to stash at each update.

## Additional Context

Any other context or screenshots or API request payload/responses that
pertain to the feature.

**Comment by soullivaneuh** [comment]
Here is my working `docker-compose.override.yml` with Traefik setup:

```yaml
version: '3.4'

services:
  router:
    # Private image based on Traefik
    image: registry.gitlab.com/company/traffic:1.1.5
    restart: always
    volumes:
      - router:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.routers.api.rule=Host(`router.sentry.company.net`)
    ports:
      - "80:80"
      - "443:443"

  nginx:
    labels:
      - traefik.enable=true
      - traefik.docker.network=company
      - traefik.http.routers.sentry.rule=Host(`sentry.company.net`)
      - traefik.http.routers.sentry.tls.certresolver=letsencrypt

networks:
  default:
    name: company

volumes:
  router: ~ 
```

With this config, I can access Sentry on https://sentry.company.net but also on http://sentry.company.net:9000 that I don't want to.
