### ISSUE TITLE
Install script crash when using a custom network

### ISSUE THREAD

**Issue by soullivaneuh** [getsentry/self-hosted#698]
In order to setup a Traefik reverse proxy, I put the following extra configuration on `docker-compose.override.yml`:

```yaml
version: '3.4'

services:
  router:
    # Private image based on Traefik
    image: registry.gitlab.com/company/traffic:1.1.5
    restart: always
    volumes:
      - router:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.routers.api.rule=Host(`router.sentry.company.net`)
    ports:
      - "80:80"
      - "443:443"

  nginx:
    labels:
      - traefik.enable=true
      - traefik.docker.network=company
      - traefik.http.routers.sentry.rule=Host(`sentry.company.net`)
      - traefik.http.routers.sentry.tls.certresolver=letsencrypt

networks:
  default:
    name: company

volumes:
  router: ~ 
```

The first install works like a charm, but the script crash on update while removing the network:

```
Docker images built.
Removing network company
error while removing network: network company id c9ac9f1a4ed7c1776415025704a5a2647dbe830c4c117c9d0b59ee902ee42c87 has active endpoints
An error occurred, caught SIGERR on line 227
Cleaning up...
```

Relaunching the script "solve" the issue.
